# Generated by Django 6.0.2 on 2026-04-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='carousel_slides/')),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which slides appear (lower number first)')),
                ('is_active', models.BooleanField(default=True, help_text='Display this slide on the homepage carousel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
